# -*- coding: utf-8 -*-
"""AnalisePri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c52eY-BVTvryp5yJMeHfW4GrYkLGOy5v
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL da página
url = 'http://www.ipeadata.gov.br/ExibeSerie.aspx?module=m&serid=1650971490&oper=view'

# Fazendo o download da página
response = requests.get(url)
html = response.content

# Parseando o HTML com BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Encontrando a tabela na página
table = soup.find('table', {'class': 'dxgvControl'})

# Extraindo os dados da tabela
data = []
for row in table.find_all('tr'):
    cols = row.find_all('td')
    if len(cols) == 2:
        data.append([cols[0].text.strip(), cols[1].text.strip()])

# Criando um DataFrame com os dados extraídos
df = pd.DataFrame(data, columns=['Data', 'Preço - petróleo bruto - Brent (FOB)'])
df = df.drop(index=df.index[:2])

df = df.reset_index(drop=True)
print(df.head())
df.to_csv('./petroleo_bruto.csv')

"""O petróleo Brent é um tipo de petróleo bruto que é extraído do Mar do Norte. É usado como referência internacional para precificação do petróleo, juntamente com o petróleo do tipo West Texas Intermediate (WTI). O preço do petróleo Brent é frequentemente utilizado como um indicador do mercado global de petróleo, e as flutuações em seu preço podem afetar os preços dos combustíveis e produtos derivados do petróleo em todo o mundo."""

# Verificar as primeiras linhas do dataframe
print(df.head())

# Verificar informações sobre o dataframe
print(df.info())

# Estatísticas descritivas básicas
print(df.describe())

# Verificar se há valores nulos
print(df.isnull().sum())

"""Tendência temporal: Plote um gráfico de linha mostrando a variação do preço do petróleo ao longo do tempo. Isso pode ajudar a identificar tendências de longo prazo."""

import matplotlib.pyplot as plt

# Converter a coluna de data para o tipo datetime
df['Data'] = pd.to_datetime(df['Data'])

# Ordenar o dataframe pela coluna de data, se não estiver ordenado
df = df.sort_values('Data')

import plotly.graph_objects as go

# Criar o gráfico de linha interativo
fig = go.Figure()
fig.add_trace(go.Scatter(x=df['Data'], y=df['Preço - petróleo bruto - Brent (FOB)'], mode='lines+markers', name='Preço do Petróleo'))
fig.update_layout(title='Variação do Preço do Petróleo ao Longo do Tempo',
                  xaxis_title='Data',
                  yaxis_title='Preço em Dólar',
                  xaxis=dict(rangeslider=dict(visible=True)),
                  template='plotly_white')
fig.show()

"""Análise de sazonalidade: Explore se há padrões sazonais na variação do preço do petróleo ao longo dos meses ou anos. Isso pode ser útil para entender como eventos sazonais afetam os preços."""

# Converter a coluna de data para o tipo datetime
df['Data'] = pd.to_datetime(df['Data'], format='%d/%m/%Y')

# Extrair o mês e o ano da coluna de data
df['Mês'] = df['Data'].dt.month
df['Ano'] = df['Data'].dt.year

# Calcular a média do preço do petróleo para cada mês ao longo dos anos
media_por_mes = df.groupby(['Mês']).mean()['Preço - petróleo bruto - Brent (FOB)']

# Plotar o gráfico de linha da média do preço do petróleo por mês
plt.figure(figsize=(12, 6))
plt.plot(media_por_mes.index, media_por_mes.values, color='green', marker='o', linestyle='-')
plt.title('Média do Preço do Petróleo por Mês')
plt.xlabel('Mês')
plt.ylabel('Preço em Dólar')
plt.xticks(range(1, 13), ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'])
plt.grid(True)
plt.show()

# Verificar os primeiros valores na coluna "Preço"
print(df['Preço - petróleo bruto - Brent (FOB)'].head())

# Remover vírgulas e converter para números
df['Preço - petróleo bruto - Brent (FOB)'] = df['Preço - petróleo bruto - Brent (FOB)'].str.replace(',', '.').astype(float)

# Remover vírgulas e converter para números na coluna de preço
df['Preço'] = df['Preço - petróleo bruto - Brent (FOB)'].str.replace(',', '.').astype(float)