

create-env:
	@python3 -m venv .env
	@echo "Execute o comando abaixo para criar o ambiente virtual"
	@echo "source ./.env/bin/activate"

run:
	streamlit run ./app.py

install:
	pip install -r requirements.txt

help:
	@echo "create-env : Cria seu ambiente virtual"
	@echo "run : Executa o programa usando Streamlit"
